### ISSUE TITLE
Math.Distance()

### ISSUE THREAD

**Issue by martinlindhe** [johnfking/mq-definitions#18]
The definition of Math.Distance() is imcomplete

https://github.com/johnfking/mq-definitions/blob/290fdc9da16d1a60a2a7e41276cf93bc70c6bfab/datatype/_math.lua#L18-L21

According to the [docs](https://docs.macroquest.org/reference/data-types/datatype-math/):
```
float 	Distance[**y,x,z:y,x,z]** 	

    Calculates the distance between two points on the map
    1, 2, or 3 dimensions may be provided
    Defaults to your character's current location
```

This means up to 3 parameters, such as this valid usage:

```lua
-- returns true if location is within maxDistance
---@return boolean
function is_within_distance_to_loc(y, x, z, maxDistance)
    return mq.TLO.Math.Distance(y, x, z) <= maxDistance
end
```

But with current mq-definitions, this gives the following error:

```
This function expects a maximum of 1 argument(s) but instead it is receiving 3.
```

I am not sure how to correctly update the definitions, so I opened this issue instead.

**Comment by johnfking** [comment]
The format is one, two, or three dimensions; but it's across two points, so you have a colon ":" between them (because of the colon, it needs to be a string...).  For example "100, 100, 25 : 225, 244, 35".  This is part of the old MQ Macro Language where everything is a string... The TLO takes one argument; a string.

**Comment by martinlindhe** [comment]
Right, that makes sense. Thank you @johnfking.
Yea, then we should just use a string and not like in my example where I hide the fact it's a string.
